# Copyright 2026 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.12-slim

WORKDIR /app
COPY app.py .

ENV SERVICE_NAME=frontend
ENV SERVICE_VERSION=v1
ENV PEER_SERVICE=checkout
ENV GENERATE_TRAFFIC=true
ENV WORK_MS=0
EXPOSE 8080

CMD ["python", "-u", "app.py"]
